### ISSUE TITLE
Missing license information?

### ISSUE THREAD

**Issue by mo** [skidding/flatris#22]
Looks like a great example to learn React from, but there is no license information in the package.json file and no LICENSE file checked in?

**Comment by skidding** [comment]
Done 31e2ddf1b276d29c2597225eaa5a5fd8d968782c and done a8eb95284ef72653d1f2ac8694152fa9eccc39e4

**Comment by mo** [comment]
Thanks for clarify this... I will recommend this project when people ask for "a well-written react project"

**Comment by skidding** [comment]
Thanks! 🙌
