### ISSUE TITLE
windows user

### ISSUE THREAD

**Issue by lanxxg** [skidding/flatris#26]
Windows command prompts will choke when set environment variables with `NODE_ENV=development cosmos` like that，use `cross-env ` for all platforms，maybe

**Comment by skidding** [comment]
Thanks @lanxxg for pointing this out. I removed NODE_ENV from package scripts altogether b7771c1d213a931a7a7cce163b374a478cdc0f8c and made Cosmos set it implicitly like Create React App does https://github.com/react-cosmos/react-cosmos/pull/497/commits/76bd0f77b31ccf6ff6963c435aa35eb97a5c1ce4. Let me know if this fixes your issue.

**Comment by lanxxg** [comment]
I've tried load flatris in my new project and run `npm run cosmos` ,it wroks. Thank you.
