### ISSUE TITLE
backend server 

### ISSUE THREAD

**Issue by Sbeaute** [skidding/flatris#61]
i want to know how you build your backend server if you have the code for that

**Comment by skidding** [comment]
@Sbeaute All the code is in this repo. It's built using Express and Socket.IO.

**Comment by skidding** [comment]
What you're asking is too vague so I'm afraid I can't answer it. You can use any backend you want. React is just a UI library. Sorry but this doesn't have anything to do with Flatris.

FYI the server code is here: https://github.com/skidding/flatris/tree/master/server

Best of luck!

**Comment by Sbeaute** [comment]
![img_1058](https://user-images.githubusercontent.com/39742893/44355268-28aa1280-a47a-11e8-8d6c-2cb2341b14cf.jpg)
![img_1057](https://user-images.githubusercontent.com/39742893/44355281-3364a780-a47a-11e8-8b7d-8c86be107d1a.jpg)
